
services:
  # NGINX Forward Proxy
  nginx-forward-proxy:
    image: dominikbechstein/nginx-forward-proxy:latest
    container_name: nginx-forward-proxy
    network_mode: host
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/htpasswd:/etc/nginx/htpasswd
    restart: unless-stopped

  # Management UI
  proxy-guard-ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: proxy-guard-ui
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./nginx:/etc/nginx
    depends_on:
      - nginx-forward-proxy
    restart: on-failure:3
    environment:
      - NODE_ENV=production
